"""""""""""""""""""""""""""""""""""""""""
" vimrc
" Author: Rui Pinheiro
"
" Vim/Neovim configuration file
"""""""""""""""""""""""""""""""""""""""""

" Disable vimrc compatibility mode
set nocompatible

" Detect vimrc file path
function! GetVimrcPath()
	let symlinkpath = $HOME . "/.vimrc"
	let realpath = resolve(symlinkpath)
	let dirname = fnamemodify(realpath, ":h")
	return dirname
endfunction
let $VIMRC_PATH = GetVimrcPath()

" Configuration file
source $VIMRC_PATH/vimrc_config.vim

" Vimscript utilities
source $VIMRC_PATH/vimrc_utils.vim

" Plugins
source $VIMRC_PATH/plugins.vim

" Tab/Spaces
source $VIMRC_PATH/tabs.vim

" Input
source $VIMRC_PATH/input.vim

" Miscellaneous
source $VIMRC_PATH/misc.vim

" Tmux
source $VIMRC_PATH/tmux.vim

" Auto Highlight
source $VIMRC_PATH/auto_highlight.vim
