"""""""""""""""""""""""""""""""""""""""""
" vimrc
" Author: Rui Pinheiro
"
" Vim/Neovim configuration file
"""""""""""""""""""""""""""""""""""""""""

" Disable vimrc compatibility mode
set nocompatible

" Detect vimrc file path
function! GetVimrcPath()
	let symlinkpath = $HOME . "/.vimrc"
	let realpath = resolve(symlinkpath)
	let dirname = fnamemodify(realpath, ":h")
	return dirname
endfunction
let $VIMRC_PATH = GetVimrcPath()

" Helper function to source dotfiles
" If $LOCAL_DOTFILES is defined, searches for a local version of the loaded dotfile
function! SourceDotfile(fname)
	" Load main version
	execute 'source ' . $VIMRC_PATH . '/' . a:fname . ''

	" Load local version
	if !empty($LOCAL_DOTFILES)
		let local_fpath= $LOCAL_DOTFILES . '/vim/' . a:fname

		if filereadable(local_fpath)
			execute 'source "' . local_fpath . '"' 
		endif
	endif
endfunction

" Configuration file
call SourceDotfile('vimrc_config.vim')

" Vimscript utilities
call SourceDotfile('vimrc_utils.vim')

" Plugins
call SourceDotfile('plugins.vim')

" Tab/Spaces
call SourceDotfile('tabs.vim')

" Input
call SourceDotfile('input.vim')

" Miscellaneous
call SourceDotfile('misc.vim')

" Tmux
call SourceDotfile('tmux.vim')

" Auto Highlight
call SourceDotfile('auto_highlight.vim')

" Local vimrc file
if !empty($VIMRC_LOCAL_PATH)
	source $VIMRC_LOCAL_PATH/vimrc_local.vim
endif
