#!/bin/bash

shopt -s extglob

##################
# Parameters
sed_exprs=()
sed_exprs_main=()
git_args=()
refs=()
files=()

color=0
color_arg=""

use_alias=1
highlight=1

function _color_auto {
  color=0
  [[ -t 1 ]] && color=1
}
_color_auto

function _parse_args {
  local saw_files=0

  while [[ "$#" -gt "0" ]]; do
    case "$1" in
      # Color arguments
      "--color"|"--color=always")
        color=1
        ;;
      "--no-color"|"--color=never")
        color=0
        ;;
      "--color=auto")
        _color_auto
        ;;
      # Highlight refs
      "--highlight")
        highlight=1
        ;;
      "--no-highlight")
        highlight=0
        ;;
      # Whether to use the 'graph' alias or not
      "--no-alias")
        use_alias=0
        ;;
      # Special git-log arguments that have a second parameter, e.g. '-n <number>'
      "-n")
        git_args+=("$1" "$2")
        shift 1
        ;;
      # used to distinguish refs from files
      "--")
        saw_files=1
        ;;
      "-"*)
        git_args+=("$1")
        ;;
      # References / file names
      *)
        # This should be a file name
        if [[ "$saw_files" -eq "1" ]]; then
          files+=("$1")
        # This should be a reference
        else
          refs+=("$1")
        fi
        ;;
    esac
    shift 1
  done

  # Colors
  if [[ "$color" -ne "0" ]]; then
    color_arg="--color"
  else
    color_arg="--no-color"
  fi
}
_parse_args "$@"


##################
# get git-config parameters
function _parse_cfg {
  local tmp_cfg_args=() has_format=0

  # Get 'graph' alias from config
  if [[ "$use_alias" -ne "0" ]]; then
    local graph_alias_name="graph"
    local tmp_cfg_args=($(git config --get "alias.${graph_alias_name}"))
  fi

  if [[ "${#tmp_cfg_args[@]}" -eq "0" || "${tmp_cfg_args[0]}" != "log" ]]; then
    echo "Warning: Could not find a valid 'git graph' alias, using defaults"

  else
    # Strip away 'log'
    tmp_cfg_args=("${tmp_cfg_args[@]:1}")

    # Correct shell expansion to fix quotes in the middle of strings
    local saw_quotes=""
    while [[ "${#tmp_cfg_args[@]}" -gt "0" ]]; do
      local x="${tmp_cfg_args[0]}"

      # Find unterminated quotes inside parameters
      if [[ ! -z "$saw_quotes" ]]; then
        [[ "$x" == !(*\\)"$saw_quotes" ]] && saw_quotes=""
        cfg_args[-1]="${cfg_args[-1]} $x"

      else
        [[ "$x" == !(*\'*)'"'* ]] && saw_quotes='"'
        [[ "$x" == !(*\"*)"'"* ]] && saw_quotes="'"
        cfg_args+=("$x")
      fi

      tmp_cfg_args=("${tmp_cfg_args[@]:1}")
    done

    # Prepend '%h %p ' to pretty-print format
    local i=0
    while [[ "${#cfg_args[@]}" -gt "$i" ]]; do
      local x="${cfg_args[$i]}"

      if [[ "$x" == "--format="* || "$x" == "--pretty"* ]]; then
        local fmt has_tformat=0
        fmt="${x#--format=}"
        fmt="${fmt#--pretty=}"

        [[ "$fmt" != ?(t)"format:"* ]] && echo "ERROR: Cannot parse 'git graph' alias. Parameter '$x' not supported by custom git-graph script" && exit 1
        [[ "$fmt" == "t"* ]] && has_tformat=1

        fmt="${fmt#t}"
        fmt="${fmt#format:}"
        
        # unquote/trim
        fmt="$(echo "$fmt" | xargs)"

        # prepend %h %p
        fmt="@%h% p@$fmt"

        # re-quote
        if [[ "$has_tformat" -eq "0" ]]; then
          fmt="--format=format:$fmt"
        else
          fmt="--format=tformat:$fmt"
        fi

        # store back in array
        cfg_args[$i]="$fmt"
        has_format=1
        break
      fi

      i=$((i+1))
    done
  fi

  # If no '--format' specified, choose the default
  [[ "$has_format" -eq "0" ]] && cfg_args+=("--format=format:@%h% p@%C(yellow)%h%C(cyan)%d%Creset %s")

  #echo "${#cfg_args[@]}: ${cfg_args[@]}"
}
cfg_args=()
_parse_cfg

[[ "$color" -eq "0" ]] && highlight=0

##################
# Parse references

function _parse_refs {
  # start with clean refs
  refs=()

  # highlighting control codes
  c_hl='\x1B\[7m'
  c_hlrst='\x1B\[27m'

  # Figure out which refs are branches/tags and which are commits, and add the relevant regexes
  while [[ "$#" -gt "0" ]]; do
    if [[ ! -z "$1" ]]; then
      local br sha
      br="$(git rev-parse --verify -q --abbrev-ref "$1")"
      [[ "$?" -ne "0" ]] && echo "ERROR: '$1' is not a valid reference" && exit 1
      sha="$(git rev-parse --verify -q --short "$1")"
      [[ "$?" -ne "0" || -z "$sha" ]] && echo "ERROR: '$1' is not a valid reference" && exit 2

      if [[ -z "$br" ]]; then
        # commit hash
        refs+=("$sha")
      else
        # branch name
        refs+=("$br")
      fi

      # Add highlighting sed command
      [[ "$highlight" -ne "0" ]] && sed_exprs+=(-e '~s~£@(.*'"$sha"'.*)$~'"$c_hl"'\1'"$c_hlrst"'~')
    fi
    shift 1
  done
}
_parse_refs "${refs[@]}"



##################
# Symbols
# Don't use fancy non-ASCII symbols outside of UTF8 locales
if [[ "$LANG" != *'utf8'* ]]; then
  commit_sym='*'
  merge_sym='>'

else
  # make the graph prettier
  commit_sym=$'\u25cf'
  merge_sym=$'\u25d0'

  sed_exprs+=(-e '~s~\|~'$'\u2502''~g') # |
  sed_exprs+=(-e '~s~/~'$'\u2571''~g' ) # /
  sed_exprs+=(-e '~s~\\~'$'\u2572''~g') # \
fi


##################
# Main expressions
# The prefixed hashes are delimited by '@'
# We replace these with '£@' for other regexes to use
re_sha='\<[a-f0-9]{7,}\>\s?'
sed_exprs_main+=(-e '~s~^(.*)\*(.*)@('"$re_sha"'){3,}\@~\1'"$merge_sym"'\2£@~') # merge commits
sed_exprs_main+=(-e '~s~^(.*)\*(.*)@('"$re_sha"')+@~\1'"$commit_sym"'\2£@~') # normal commits

# clean up any remaining '£@'
# NOTE: Must be the last expression
sed_exprs+=(-e '~s~£@~~')


##################
# Actual command
git log "${cfg_args[@]}" --graph "$color_arg" "${git_args[@]}" "${refs[@]}" -- "${files[@]}" \
  | sed -E "${sed_exprs_main[@]}" "${sed_exprs[@]}" \
  | ${PAGER:-less}
