- name: Create neovim directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  with_items:
    - ~/.config/nvim
    - ~/.local/share/nvim/site/autoload

- name: Symlink ~/dotfiles/vim/vimrc to ~/.config/nvim/init.vim
  ansible.builtin.file:
    src: ../../dotfiles/vim/vimrc
    path: ~/.config/nvim/init.vim
    state: link

- name: Download vim-plug for neovim
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
  register: neovim_vimplug

- name: Update neovim plugins
  ansible.builtin.command: nvim +PlugUpdate +qall
  changed_when: neovim_vimplug.changed
  register: neovim_plugins

- name: Update neovim remote plugins
  ansible.builtin.command: nvim +UpdateRemotePlugins +qall
  changed_when: neovim_plugins.changed