#########################################
# zshrc
# Author: Rui Pinheiro
#
# Zsh configuration file

export USE_ZSH="1"

export ZSH_HOME=$(dirname "$(readlink -f "${(%):-%N}")" )
source $ZSH_HOME/zsh_init.zsh
